const $=id=>document.getElementById(id);
const STATES=['未做过','做错了','做对了'];
let catalog,progress={},current=null,records=[],queue=[],state=STATES[0],images=[],selectedOption=null,loading=0,uploading=0,saving=false,toastTimer,filterChapter=null,filterSection=null,libraryMatches=[],libraryLimit=60,submissionToken=null;
const text=(tag,value,cls)=>{const el=document.createElement(tag);el.textContent=value;if(cls)el.className=cls;return el};
const reduceMotion=()=>matchMedia('(prefers-reduced-motion: reduce)').matches;
const sourceUrl=(q,relative)=>'/source/'+q.sourceDir.split('/').map(encodeURIComponent).join('/')+'/'+relative.split('/').map(encodeURIComponent).join('/');
function notify(message){$('toast').textContent=message;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),3500)}
async function api(url,options={}){const response=await fetch(url,options);const data=await response.json();if(!response.ok)throw Error(data.error||'请求没有完成');return data}
const post=(url,payload)=>api(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});
function showImage(url){$('fullImage').src=url;$('imageViewer').showModal();$('fullImage').tabIndex=-1;$('fullImage').focus({preventScroll:true})}
function markdown(container,raw,q=null){
  const math=[];
  const protectedText=(raw||'').replace(/(```[\s\S]*?```|`[^`\n]+`)|\$\$([\s\S]*?)\$\$|\$([^$\n]+)\$|\\\[([\s\S]*?)\\\]|\\\(([^\n]*?)\\\)/g,(all,code,display,inline,bracket,paren)=>{
    if(code)return code;const index=math.length;math.push({tex:display??inline??bracket??paren,display:display!==undefined||bracket!==undefined});return `<span data-math="${index}"></span>`;
  });
  container.innerHTML=DOMPurify.sanitize(marked.parse(protectedText,{gfm:true,breaks:true}),{ADD_ATTR:['data-math'],FORBID_TAGS:['style','iframe','form','input','button','video','audio']});
  container.querySelectorAll('[data-math]').forEach(el=>{const value=math[Number(el.dataset.math)];if(value)katex.render(value.tex,el,{displayMode:value.display,throwOnError:false,trust:false,strict:'ignore'});el.removeAttribute('data-math')});
  container.querySelectorAll('img').forEach(img=>{const original=img.getAttribute('src')||'';if(q&&!/^(?:https?:|data:|\/)/i.test(original))img.src=sourceUrl(q,original);else if(!original.startsWith('/media/')&&!q)img.remove();if(!img.isConnected)return;img.loading='lazy';img.tabIndex=0;img.setAttribute('role','button');img.setAttribute('aria-label','查看原图：'+(img.alt||'题目图片'));img.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();showImage(img.src)});img.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();e.stopPropagation();showImage(img.src)}})});
  container.querySelectorAll('table').forEach(table=>{const wrap=document.createElement('div');wrap.className='table-wrap';table.replaceWith(wrap);wrap.append(table)});
  container.querySelectorAll('a').forEach(a=>{const href=a.getAttribute('href')||'';if(q&&!/^(?:https?:|\/|#)/i.test(href))a.href=sourceUrl(q,href);a.target='_blank';a.rel='noopener noreferrer'});
}
function updateSave(){ $('save').disabled=!current||saving||uploading>0; $('save').firstElementChild.textContent=saving?'正在保存…':uploading?'正在保存图片…':'＋ 保存记录' }
function draftKey(){return current?'shiqi-draft-'+current.id:null}
function keepDraft(){submissionToken=null;if(!current)return;try{localStorage.setItem(draftKey(),JSON.stringify({state,note:$('noteText').value,images,selectedOption}))}catch{notify('浏览器草稿未能保存，请及时提交记录')}}
function setState(value,keep=true){state=value;document.querySelectorAll('[data-state]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.state===value)));$('statusMark').style.transform=`translateX(${STATES.indexOf(value)*100}%)`;if(keep)keepDraft()}
function renderAttachments(){ $('attachments').replaceChildren();images.forEach((url,i)=>{const item=text('div','','attachment');const open=document.createElement('button');open.type='button';open.setAttribute('aria-label','查看笔记图片 '+(i+1));const img=document.createElement('img');img.src=url;img.alt='笔记图片';open.append(img);open.onclick=()=>showImage(url);const remove=text('button','×');remove.setAttribute('aria-label','移除笔记图片 '+(i+1));remove.onclick=()=>{images.splice(i,1);renderAttachments();keepDraft()};item.append(open,remove);$('attachments').append(item)}) }
async function addImages(files){if(!current)return;const qid=current.id;uploading++;updateSave();try{for(const file of files){if(!file.type.startsWith('image/'))continue;if(file.size>12*1024*1024){notify('图片需小于 12 MB');continue}if(images.length>=30){notify('每次记录最多 30 张图片');break}const result=await api('/api/upload',{method:'POST',headers:{'Content-Type':file.type},body:file});if(current?.id===qid){images.push(result.url);renderAttachments();keepDraft()}else{const key='shiqi-draft-'+qid;const draft=JSON.parse(localStorage.getItem(key)||'{}');(draft.images??=[]).push(result.url);localStorage.setItem(key,JSON.stringify(draft))}}}catch(e){notify('图片未保存：'+e.message)}finally{uploading--;updateSave()}}
function selected(){document.querySelectorAll('.option').forEach(b=>{const active=b.dataset.label===selectedOption;b.classList.toggle('chosen',active);b.setAttribute('aria-pressed',String(active))})}
function dateLabel(value){return new Date(value).toLocaleString('zh-CN',{year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false})}
function renderRecords(){ $('records').replaceChildren();$('recordCount').textContent=String(records.length).padStart(2,'0');if(!records.length){$('records').append(text('p','这里会留下每一次尝试。','history-empty'));return}records.slice().reverse().forEach((record,i)=>{const button=text('button','','record');const label=text('span',record.state);label.append(text('span',`第 ${records.length-i} 轮 · ${dateLabel(record.createdAt)}${record.images.length?' · 含图片':''}`));button.append(label,text('span','↗'));button.onclick=()=>{$('recordTitle').textContent=`第 ${records.length-i} 轮 / ${record.state} / ${dateLabel(record.createdAt)}`;markdown($('recordBody'),record.note||'本轮仅记录了做题状态。');if(record.selectedOption)$('recordBody').prepend(text('p','当时选择：'+record.selectedOption));$('recordImages').replaceChildren();record.images.forEach(url=>{const b=text('button','','record-image-button');b.setAttribute('aria-label','打开本轮笔记图片');const img=document.createElement('img');img.src=url;img.alt='这次记录的图片';img.className='record-image';b.append(img);b.onclick=()=>showImage(url);$('recordImages').append(b)});$('recordViewer').showModal()};$('records').append(button)}) }
function updateProgress(){const active=catalog.questions.filter(q=>progress[q.id]?.state!=='未做过'&&progress[q.id]);$('progressLabel').textContent=`已做 ${active.length} / ${catalog.total}　·　错题 ${active.filter(q=>progress[q.id].state==='做错了').length}`}
function renderQueue(){const pos=queue.findIndex(q=>q.id===current.id);$('position').textContent=String(pos+1).padStart(2,'0');$('queueCount').textContent=queue.length;$('previous').disabled=pos<=0;$('next').disabled=pos<0||pos>=queue.length-1;$('trackActive').style.left=`${queue.length>1?pos/(queue.length-1)*100:0}%`}
function reveal(){if(reduceMotion())return;const el=$('questionContent');el.getAnimations().forEach(a=>a.cancel());el.animate([{opacity:.2,transform:'translateY(7px)',clipPath:'inset(0 0 100% 0)'},{opacity:1,transform:'translateY(0)',clipPath:'inset(0 0 0% 0)'}],{duration:450,easing:'cubic-bezier(.22,1,.36,1)'})}
async function openQuestion(id,newQueue=null,label='当前小节',feedback=false){
  if(saving){notify('记录正在保存，请稍等');return}keepDraft();const revision=++loading;try{const [q,history]=await Promise.all([api('/api/questions/'+encodeURIComponent(id)),api('/api/records?questionId='+encodeURIComponent(id))]);if(revision!==loading)return;current=q;records=history;queue=newQueue||catalog.questions.filter(x=>x.sectionId===q.sectionId);$('queueLabel').textContent=label;
  $('sectionTitle').textContent=q.section;$('sectionBreadcrumb').textContent=`${String(q.chapterNumber).padStart(2,'0')} / ${q.chapter}`;$('sectionDescription').textContent=`${q.sectionId}　${q.type} · 第 ${q.number} 题`;$('questionType').textContent=q.type;$('questionId').textContent=`${q.sectionId} / ${q.options.length?'Q':'F'}${String(q.number).padStart(3,'0')}`;$('questionId').title=q.id;$('questionNumber').textContent=String(q.number).padStart(2,'0');$('sourceLabel').textContent=catalog.archive?.subject||'本地题库';markdown($('questionText'),q.stem,q);$('options').replaceChildren();q.options.forEach(option=>{const b=text('button','','option');b.dataset.label=option.label;b.setAttribute('aria-pressed','false');const content=text('span','','markdown option-label');markdown(content,option.markdown,q);b.append(text('span',option.label,'letter'),content,text('span','✓','check'));b.onclick=()=>{if(selectedOption!==option.label)FieldSound.play('select');selectedOption=option.label;selected();keepDraft()};$('options').append(b)});
  $('answerText').replaceChildren();$('answerText').append(text('p','REFERENCE ANSWER / 参考答案','answer-label'));const answer=text('div','','markdown');markdown(answer,q.answer,q);$('answerText').append(answer);if(q.explanation){$('answerText').append(text('p','ANALYSIS / 详细解析','answer-label'));const exp=text('div','','markdown');markdown(exp,q.explanation,q);$('answerText').append(exp)};$('answerPanel').classList.remove('open');$('answerPanel').setAttribute('aria-hidden','true');$('answerToggle').setAttribute('aria-expanded','false');$('answerToggle').firstElementChild.textContent='查看答案与解析';$('referenceArea').replaceChildren();for(const [name,raw] of [['图示与参考资料',q.reference],['提取附记',q.diagnostic]]){if(!raw)continue;const details=text('details','','source-details');details.append(text('summary',name));const body=text('div','','markdown');markdown(body,raw,q);details.append(body);details.addEventListener('toggle',()=>{if(details.isConnected)FieldSound.play(details.open?'reveal':'collapse')});$('referenceArea').append(details)};$('sourceNote').textContent=q.chapter+' / '+q.section;
  let draft=null;try{draft=JSON.parse(localStorage.getItem(draftKey())||'null')}catch{};images=draft?.images||[];selectedOption=draft?.selectedOption||null;$('noteText').value=draft?.note||'';setState(draft?.state&&STATES.includes(draft.state)?draft.state:(history.at(-1)?.state||STATES[0]),false);selected();renderAttachments();renderRecords();renderQueue();updateSave();document.querySelectorAll('#chapterNav button').forEach(b=>b.classList.toggle('active',Number(b.dataset.chapter)===q.chapterNumber));history.length&&(progress[q.id]={state:history.at(-1).state,attempts:history.length});updateProgress();historyReplace(id);reveal();if(feedback)FieldSound.play('navigate');
  }catch(e){notify('题目未载入：'+e.message)}
}
function historyReplace(id){history.replaceState(null,'','#'+encodeURIComponent(id))}
function renderSectionList(){const list=$('sectionList');list.replaceChildren();const all=text('button','全部章节');all.classList.toggle('selected',!filterChapter&&!filterSection);all.onclick=()=>{filterChapter=null;filterSection=null;renderSectionList();renderLibrary()};list.append(all);catalog.chapters.forEach(ch=>{const head=text('button',`${String(ch.number).padStart(2,'0')}　${ch.name}　${ch.count}`,'section-chapter');head.classList.toggle('selected',filterChapter===ch.number&&!filterSection);head.onclick=()=>{filterChapter=ch.number;filterSection=null;renderSectionList();renderLibrary()};list.append(head);ch.sections.forEach(s=>{const b=text('button',`${s.id}　${s.name}　${s.count}`);b.classList.toggle('selected',filterSection===s.id);b.onclick=()=>{filterChapter=ch.number;filterSection=s.id;renderSectionList();renderLibrary()};list.append(b)})}) }
function renderLibrary(preserve=false){if(!catalog)return;if(preserve!==true)libraryLimit=60;const term=$('search').value.trim().toLowerCase();const selectedState=$('stateFilter').value;const selectedType=$('typeFilter').value;libraryMatches=catalog.questions.filter(q=>(!filterChapter||q.chapterNumber===filterChapter)&&(!filterSection||q.sectionId===filterSection)&&(!selectedState||(progress[q.id]?.state||STATES[0])===selectedState)&&(!selectedType||q.type===selectedType)&&(!term||`${q.title} ${q.search} ${q.section} ${q.id}`.toLowerCase().includes(term)));$('resultCount').textContent=libraryMatches.length+' FILES';$('resultLabel').textContent=filterSection?catalog.chapters.flatMap(c=>c.sections).find(s=>s.id===filterSection).name:filterChapter?catalog.chapters.find(c=>c.number===filterChapter).name:'全部题目';$('questionList').replaceChildren();if(!libraryMatches.length){$('questionList').append(text('p','没有匹配的题目。','empty-results'));return}const fragment=document.createDocumentFragment();libraryMatches.slice(0,libraryLimit).forEach(q=>{const b=text('button','','question-row');b.classList.toggle('current',q.id===current?.id);const number=text('span',String(q.number).padStart(2,'0'),'row-number');const body=text('span','');let title=q.search.replace(/!\[[^\]]*\]\([^)]*\)/g,'[图]').replace(/[#*$`]/g,'').slice(0,95);body.append(text('span',title+(q.search.length>95?'…':''),'row-title'),text('span',`${q.sectionId} / ${q.section}　·　${q.type}`,'row-meta'));b.append(number,body,text('span',progress[q.id]?.state||STATES[0],'row-state'));b.onclick=()=>{const chosenQueue=[...libraryMatches];$('library').close('',true);openQuestion(q.id,chosenQueue,selectedState?'筛选结果':filterSection?'当前小节':'所选题目',true)};fragment.append(b)});$('questionList').append(fragment);if(libraryMatches.length>libraryLimit){const more=text('button',`继续显示 · 已显示 ${libraryLimit} / ${libraryMatches.length}`,'load-more');more.onclick=()=>{libraryLimit+=60;renderLibrary(true)};$('questionList').append(more)}}
function openLibrary(chapter=null,section=null){filterChapter=chapter;filterSection=section;renderSectionList();renderLibrary();$('library').showModal();$('search').focus()}
function renderChapters(){$('chapterNav').replaceChildren();catalog.chapters.forEach(ch=>{const b=document.createElement('button');b.dataset.chapter=ch.number;b.append(text('b',String(ch.number).padStart(2,'0')),text('span',ch.shortName||ch.name.slice(0,4)));b.onclick=()=>openLibrary(ch.number);$('chapterNav').append(b)})}
async function loadCatalog(){const [c,p]=await Promise.all([api('/api/catalog'),api('/api/progress')]);catalog=c;progress=p;$('brandSubject').textContent='研习档案 / '+(c.archive?.subject||'本地题库');$('signalCaption').textContent='STRUCTURE / '+(c.archive?.code||'STUDY');$('archiveCode').textContent=(c.archive?.code||'STUDY')+' / LOCAL';const previousType=$('typeFilter').value;$('typeFilter').replaceChildren(new Option('全部题型',''),...(c.types||[]).map(type=>new Option(type,type)));if(c.types?.includes(previousType))$('typeFilter').value=previousType;renderChapters();$('totalCount').textContent=c.total+' FILES';$('importInfo').textContent=`${c.chapters.length} 章 / ${c.chapters.reduce((n,ch)=>n+ch.sections.length,0)} 小节 · ${c.issues.length?'有 '+c.issues.length+' 项导入提示':'本地题库已同步'}`;if(c.issues.length)notify('有导入提示，请查看 data/catalog.json；原文件未修改');updateProgress()}
document.querySelectorAll('[data-state]').forEach(b=>b.onclick=()=>{if(state!==b.dataset.state)FieldSound.play('select');setState(b.dataset.state)});$('noteText').addEventListener('input',keepDraft);$('imageInput').onchange=e=>{addImages([...e.target.files]);e.target.value=''};$('noteText').addEventListener('paste',e=>{const files=[...(e.clipboardData?.items||[])].filter(i=>i.kind==='file'&&i.type.startsWith('image/')).map(i=>i.getAsFile()).filter(Boolean);if(files.length){e.preventDefault();addImages(files)}});
$('save').onclick=async()=>{if(!current||saving||uploading)return;const qid=current.id;const payload={questionId:qid,state,note:$('noteText').value,images:[...images],selectedOption,requestId:submissionToken||crypto.randomUUID()};submissionToken=payload.requestId;saving=true;updateSave();try{const record=await post('/api/records',payload);records.push(record);progress[qid]={state:record.state,attempts:records.length};localStorage.removeItem(draftKey());submissionToken=null;$('noteText').value='';images=[];renderAttachments();renderRecords();updateProgress();notify('已保存到本机，第 '+records.length+' 次记录。');FieldSound.play('save')}catch(e){notify('保存未完成：'+e.message+'。草稿还在。')}finally{saving=false;updateSave()}};
$('answerToggle').onclick=()=>{const open=$('answerPanel').classList.toggle('open');FieldSound.play(open?'reveal':'collapse');$('answerPanel').setAttribute('aria-hidden',String(!open));$('answerToggle').setAttribute('aria-expanded',String(open));$('answerToggle').firstElementChild.textContent=open?'收起答案与解析':'查看答案与解析'};
function move(delta){if(!current)return;const i=queue.findIndex(q=>q.id===current.id)+delta;if(queue[i])openQuestion(queue[i].id,queue,$('queueLabel').textContent,true)}$('previous').onclick=()=>move(-1);$('next').onclick=()=>move(1);
$('openLibrary').onclick=() => openLibrary();$('railSearch').onclick=()=>openLibrary();$('openSection').onclick=()=>current&&openLibrary(current.chapterNumber,current.sectionId);
['search','stateFilter','typeFilter'].forEach(id=>$(id).addEventListener(id==='search'?'input':'change',renderLibrary));
$('refreshLibrary').onclick=async()=>{const button=$('refreshLibrary');button.disabled=true;try{const result=await post('/api/refresh',{});await loadCatalog();renderSectionList();renderLibrary();notify('题库已同步，共 '+result.total+' 道题；已有记录保留。')}catch(e){notify('同步未完成：'+e.message)}finally{button.disabled=false}};
$('backup').onclick=async()=>{try{const response=await fetch('/api/backup');if(!response.ok)throw Error('备份未完成');const url=URL.createObjectURL(await response.blob());const a=document.createElement('a');a.href=url;a.download='field-archive-records-'+new Date().toLocaleDateString('sv-SE')+'.zip';a.click();setTimeout(()=>URL.revokeObjectURL(url),10000)}catch(e){notify(e.message)}};
$('copySource').onclick=async()=>{if(!current)return;try{await navigator.clipboard.writeText(catalog.sourceRoot.replace(/\/$/,'')+'/'+current.sourceFile);notify('已复制这道题的 Markdown 路径')}catch{notify('题目路径：'+current.sourceFile)}};
document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$(b.dataset.close).close());document.querySelectorAll('dialog').forEach(dialog=>{let closing=false;const show=dialog.showModal.bind(dialog);dialog.showModal=function(){if(dialog.open)return;show();FieldSound.play('open')};const finish=dialog.close.bind(dialog);dialog.close=function(returnValue='',quiet=false){if(closing||!dialog.open)return;if(!quiet)FieldSound.play('close');if(reduceMotion()){finish(returnValue);return}closing=true;dialog.animate([{opacity:1,transform:'translateY(0)'},{opacity:0,transform:'translateY(8px)'}],{duration:160,easing:'cubic-bezier(.4,0,1,1)'}).finished.then(()=>{finish(returnValue);closing=false}).catch(()=>{finish(returnValue);closing=false})};dialog.addEventListener('cancel',e=>{e.preventDefault();dialog.close()});dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close()}})});
document.addEventListener('keydown',e=>{const editing=['INPUT','TEXTAREA','SELECT'].includes(e.target.tagName);if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();if(!$('library').open)openLibrary();return}if(editing||document.querySelector('dialog[open]'))return;if(e.key==='ArrowLeft')move(-1);if(e.key==='ArrowRight')move(1)});
addEventListener('hashchange',()=>{const id=decodeURIComponent(location.hash.slice(1));if(id&&id!==current?.id&&catalog.questions.some(q=>q.id===id))openQuestion(id)});
async function syncExternal(){if(saving||uploading||!catalog)return;try{const nextProgress=await api('/api/progress');const changed=JSON.stringify(progress)!==JSON.stringify(nextProgress);progress=nextProgress;updateProgress();if(current){const qid=current.id;const latest=await api('/api/records?questionId='+encodeURIComponent(qid));if(current?.id===qid&&!saving&&JSON.stringify(latest)!==JSON.stringify(records)){records=latest;renderRecords()}}if(changed&&$('library').open)renderLibrary(true)}catch{}}
addEventListener('focus',syncExternal);document.addEventListener('visibilitychange',()=>{if(!document.hidden)syncExternal()});setInterval(()=>{if(!document.hidden)syncExternal()},15000);
FieldSound.init();
loadCatalog().then(()=>{const requested=decodeURIComponent(location.hash.slice(1));openQuestion(catalog.questions.some(q=>q.id===requested)?requested:catalog.questions[0].id)}).catch(e=>{$('sectionTitle').textContent='题库暂未载入';$('questionText').textContent='请确认本地服务已经启动。'+e.message});
